os: linux
dist: jammy
language: node_js
node_js:
  - "18"

jobs:
  include:
    - stage: coverage
      node_js: node
      script: npm run coverage && npx c8 report --reporter=text-lcov | npx coveralls
