os: linux
language: node_js
node_js:
  - "16"
  - "17"

jobs:
  include:
    - stage: coverage
      node_js: node
      script: npm run coverage && npx c8 report --reporter=text-lcov | npx coveralls
